import type { StoreRepository } from '../../domain/repositories/StoreRepository';
import {
  createStore,
  createCategory,
  createScenario,
  createSuite,
  deleteCategory,
  deleteScenario,
  deleteStore,
  deleteSuite,
  exportStoreData,
  getStoreDetail,
  listCategories,
  listScenarios,
  listStoresSummary,
  listSuites,
  listenToScenarios,
  listenToSuites,
  updateCategory,
  updateScenario,
  updateStore,
  updateSuite,
} from '../external/stores';

export const firebaseStoreRepository: StoreRepository = {
  listByOrganization: listStoresSummary,
  getById: getStoreDetail,
  listSummary: listStoresSummary,
  getDetail: getStoreDetail,
  create: createStore,
  update: updateStore,
  delete: deleteStore,
  listScenarios,
  listenToScenarios,
  createScenario,
  updateScenario,
  deleteScenario,
  listSuites,
  listenToSuites,
  createSuite,
  updateSuite,
  deleteSuite,
  listCategories,
  createCategory,
  updateCategory,
  deleteCategory,
  exportStore: exportStoreData,
};
