import type { StoreRepository } from '../../domain/repositories/StoreRepository';
import {
  createStore,
  createCategory,
  createScenario,
  createSuite,
  deleteCategory,
  deleteScenario,
  deleteStore,
  deleteSuite,
  exportStoreData,
  getStore,
  listCategories,
  listScenarios,
  listStores,
  listSuites,
  listenToScenarios,
  listenToSuites,
  uploadStoreLogo,
  updateCategory,
  updateScenario,
  updateStore,
  updateSuite,
} from '../external/stores';

export const firebaseStoreRepository: StoreRepository = {
  listByOrganization: listStores,
  getById: getStore,
  listSummary: listStores,
  getDetail: getStore,
  create: createStore,
  update: updateStore,
  uploadLogo: uploadStoreLogo,
  delete: deleteStore,
  listScenarios,
  listenToScenarios,
  createScenario,
  updateScenario,
  deleteScenario,
  listSuites,
  listenToSuites,
  createSuite,
  updateSuite,
  deleteSuite,
  listCategories,
  createCategory,
  updateCategory,
  deleteCategory,
  exportStore: exportStoreData,
};
